# Generated by Django 4.2.5 on 2023-10-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApplication', '0003_remove_news_ctreate_at_news_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время публикации'),
        ),
    ]
